{
 "title": "Dgraph-Kubernetes",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Pod", "query": "label_values(pod)" }
  ]
 },
 "panels": [
  {
   "title": "Zero and Alpha",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dgraph_alpha_health_status{pod=~'$Pod'}-1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "(dgraph_memory_idle_bytes{pod=~'$Pod'}+dgraph_memory_inuse_bytes{pod=~'$Pod'})",
     "legendFormat": "Alpha"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dgraph_memory_inuse_bytes+dgraph_memory_idle_bytes{pod=~'$Pod'}",
     "legendFormat": "Inuse+Idle ({{pod}})"
    },
    {
     "expr": "dgraph_memory_proc_bytes{pod=~'$Pod'}",
     "legendFormat": "Proc ({{pod}})"
    }
   ]
  },
  {
   "title": "Active mutations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_active_mutations_total{pod=~'$Pod'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pending Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_pending_proposals_total{pod=~'$Pod'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Heap Idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dgraph_memory_idle_bytes{pod=~'$Pod'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC second sum rate(30s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{pod=~'$Pod'}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "description": "goroutines used by go.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines{pod=~'$Pod'}", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Processed Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dgraph_num_queries_total" }
   ]
  },
  {
   "title": "Pending Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_pending_queries_total{pod=~'$Pod'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Raft Applied Index",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_raft_applied_index{pod=~'$Pod'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Server Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_alpha_health_status{pod=~'$Pod'}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}