repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: xit-prometheus
    namespace: dgraph
    chart: prometheus-community/kube-prometheus-stack
    values:
      - ./dgraph-prometheus-operator.yaml
      - grafana:
          adminPassword: andysanru
      - ./dgraph-app-alert-rules.yaml
      - ./dgraph-backup-alert-rules.yaml
    disableValidation: true